language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build  -t sergeyn0vik/dockertest -f Dockerfile.dev .

script:
 - docker run -e CI=true sergeyn0vik/dockertest npm run test -- --coverage